name: flutter_playground
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  archive: any
  audioplayers: any
  # > The version constraint is optional but recommended. If no version constraint is given, any is assumed.
  # https://dart.dev/tools/pub/dependencies#hosted-packages
  device_info_plus: any
  encrypt: any
  firebase_analytics: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  flutter_local_notifications: any
  flutter_localizations: # https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
    sdk: flutter
  flutter_riverpod: any
  flutter_slidable: any
  flutter_sound: any
  flutter_svg: any
  freezed_annotation: any
  gal: any
  geolocator: any
  glob: any
  http: any
  image_picker: any
  image_picker_android: any
  image_picker_platform_interface: any
  intl: any
  json_annotation: any
  location: any
  path: any
  path_provider: any
  permission_handler: any
  riverpod_annotation: any
  shared_preferences: any
  showcaseview: any
  tutorial_coach_mark: any
  upgrader: any
  url_launcher: any
  video_player: any
  webview_flutter: any
dev_dependencies:
  build_runner: any
  custom_lint: any
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  riverpod_generator: any
  riverpod_lint: any
flutter:
  generate: true # https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
  uses-material-design: true
